### ISSUE TITLE
Getting a few errors please help

### ISSUE THREAD

**Issue by zlite4** [starton-io/twitter-airdrop-bot#1]
Im getting these errors running on my linux 18.04
After running npm install
npm WARN starton-quote-retweet@1.0.0 No repository field.

Also when I run fetchTweet.js

/home/me/twitter-airdrop-bot/node_modules/twitter-api-v2/dist/paginators/TwitterPaginator.js:110
    async *[Symbol.asyncIterator]() {
          ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/me/twitter-airdrop-bot/node_modules/twitter-api-v2/dist/paginators/paginator.v1.js:7:44)

Im using npm-3.5.2 and node-8.10.0

How to fix?

**Comment by philippe-desplats** [comment]
Hello @XziimP,

Thank you for reporting the bug you encountered.

We have taken into consideration the bug you are experiencing. We will be updating the project shortly to fix the problem with `twitter-api-v2`.

We will keep you informed when it is done.

See you soon 🚀

**Comment by philippe-desplats** [comment]
Hello @XziimP,

The problem should be solved normally. Could you confirm this so that we can close the exit?

Thank you and have a nice day.
